@startuml

title Жизненный цикл соединения в пуле

start

:Корутина вызывает\n$pdo->query();

if (Есть соединение\nдля этой корутины?) then (да)
    :Использовать его;
else (нет)
    :Взять из пула\nили создать новое;
endif

:Выполнить запрос,\nвернуть $stmt;

if ($stmt уничтожен?) then (да)
    if (Активная\nтранзакция?) then (да)
        :Соединение остаётся\nза корутиной;
    else (нет)
        :Вернуть соединение\nв пул;
    endif
else (нет)
    :Соединение остаётся\nза корутиной;
endif

stop

@enduml
