import type { NavGroup } from './sidebarData'

export const docsSidebarFr: NavGroup[] = [
  {
    title: 'Premiers pas',
    icon: 'section-rocket',
    items: [
      { url: '/fr/docs.html', label: 'Introduction' },
      { url: '/fr/docs/components/introduction.html', label: "Pourquoi l'asynchronisme ?" },
    ],
  },
  {
    title: 'Configuration',
    icon: 'section-settings',
    items: [
      { url: '/fr/docs/reference/ini-settings.html', label: 'Paramètres INI' },
    ],
  },
  {
    title: 'Composants',
    icon: 'section-blocks',
    items: [
      {
        url: '/fr/docs/components/coroutines.html',
        label: 'Coroutine',
        icon: 'zap',
        children: [
          { url: '/fr/docs/reference/coroutine/get-id.html', label: 'getId()' },
          { url: '/fr/docs/reference/coroutine/get-context.html', label: 'getContext()' },
          { url: '/fr/docs/reference/coroutine/get-result.html', label: 'getResult()' },
          { url: '/fr/docs/reference/coroutine/get-exception.html', label: 'getException()' },
          { url: '/fr/docs/reference/coroutine/is-started.html', label: 'isStarted()' },
          { url: '/fr/docs/reference/coroutine/is-queued.html', label: 'isQueued()' },
          { url: '/fr/docs/reference/coroutine/is-running.html', label: 'isRunning()' },
          { url: '/fr/docs/reference/coroutine/is-suspended.html', label: 'isSuspended()' },
          { url: '/fr/docs/reference/coroutine/is-completed.html', label: 'isCompleted()' },
          { url: '/fr/docs/reference/coroutine/is-cancelled.html', label: 'isCancelled()' },
          { url: '/fr/docs/reference/coroutine/is-cancellation-requested.html', label: 'isCancellationRequested()' },
          { url: '/fr/docs/reference/coroutine/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/coroutine/as-hi-priority.html', label: 'asHiPriority()' },
          { url: '/fr/docs/reference/coroutine/on-finally.html', label: 'finally()' },
          { url: '/fr/docs/reference/coroutine/get-trace.html', label: 'getTrace()' },
          { url: '/fr/docs/reference/coroutine/get-spawn-file-and-line.html', label: 'getSpawnFileAndLine()' },
          { url: '/fr/docs/reference/coroutine/get-spawn-location.html', label: 'getSpawnLocation()' },
          { url: '/fr/docs/reference/coroutine/get-suspend-file-and-line.html', label: 'getSuspendFileAndLine()' },
          { url: '/fr/docs/reference/coroutine/get-suspend-location.html', label: 'getSuspendLocation()' },
          { url: '/fr/docs/reference/coroutine/get-awaiting-info.html', label: 'getAwaitingInfo()' },
        ],
      },
      {
        url: '/fr/docs/components/scope.html',
        label: 'Scope',
        icon: 'braces',
        children: [
          { url: '/fr/docs/reference/scope/inherit.html', label: 'inherit()' },
          { url: '/fr/docs/reference/scope/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/scope/as-not-safely.html', label: 'asNotSafely()' },
          { url: '/fr/docs/reference/scope/spawn.html', label: 'spawn()' },
          { url: '/fr/docs/reference/scope/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/scope/await-completion.html', label: 'awaitCompletion()' },
          { url: '/fr/docs/reference/scope/await-after-cancellation.html', label: 'awaitAfterCancellation()' },
          { url: '/fr/docs/reference/scope/is-finished.html', label: 'isFinished()' },
          { url: '/fr/docs/reference/scope/is-closed.html', label: 'isClosed()' },
          { url: '/fr/docs/reference/scope/is-cancelled.html', label: 'isCancelled()' },
          { url: '/fr/docs/reference/scope/set-exception-handler.html', label: 'setExceptionHandler()' },
          { url: '/fr/docs/reference/scope/set-child-scope-exception-handler.html', label: 'setChildScopeExceptionHandler()' },
          { url: '/fr/docs/reference/scope/on-finally.html', label: 'finally()' },
          { url: '/fr/docs/reference/scope/dispose.html', label: 'dispose()' },
          { url: '/fr/docs/reference/scope/dispose-safely.html', label: 'disposeSafely()' },
          { url: '/fr/docs/reference/scope/dispose-after-timeout.html', label: 'disposeAfterTimeout()' },
          { url: '/fr/docs/reference/scope/get-child-scopes.html', label: 'getChildScopes()' },
          { url: '/fr/docs/reference/scope/provide-scope.html', label: 'provideScope()' },
        ],
      },
      {
        url: '/fr/docs/components/channels.html',
        label: 'Channels',
        icon: 'arrow-left-right',
        children: [
          { url: '/fr/docs/reference/channel/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/channel/send.html', label: 'send()' },
          { url: '/fr/docs/reference/channel/send-async.html', label: 'sendAsync()' },
          { url: '/fr/docs/reference/channel/recv.html', label: 'recv()' },
          { url: '/fr/docs/reference/channel/recv-async.html', label: 'recvAsync()' },
          { url: '/fr/docs/reference/channel/close.html', label: 'close()' },
          { url: '/fr/docs/reference/channel/is-closed.html', label: 'isClosed()' },
          { url: '/fr/docs/reference/channel/capacity.html', label: 'capacity()' },
          { url: '/fr/docs/reference/channel/count.html', label: 'count()' },
          { url: '/fr/docs/reference/channel/is-empty.html', label: 'isEmpty()' },
          { url: '/fr/docs/reference/channel/is-full.html', label: 'isFull()' },
          { url: '/fr/docs/reference/channel/get-iterator.html', label: 'getIterator()' },
        ],
      },
      {
        url: '/fr/docs/components/future.html',
        label: 'Future',
        icon: 'clock',
        children: [
          { url: '/fr/docs/reference/future/completed.html', label: 'completed()' },
          { url: '/fr/docs/reference/future/failed.html', label: 'failed()' },
          { url: '/fr/docs/reference/future/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/future/is-completed.html', label: 'isCompleted()' },
          { url: '/fr/docs/reference/future/is-cancelled.html', label: 'isCancelled()' },
          { url: '/fr/docs/reference/future/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/future/ignore.html', label: 'ignore()' },
          { url: '/fr/docs/reference/future/map.html', label: 'map()' },
          { url: '/fr/docs/reference/future/catch.html', label: 'catch()' },
          { url: '/fr/docs/reference/future/finally.html', label: 'finally()' },
          { url: '/fr/docs/reference/future/await.html', label: 'await()' },
          { url: '/fr/docs/reference/future/get-awaiting-info.html', label: 'getAwaitingInfo()' },
          { url: '/fr/docs/reference/future/get-created-file-and-line.html', label: 'getCreatedFileAndLine()' },
          { url: '/fr/docs/reference/future/get-created-location.html', label: 'getCreatedLocation()' },
          { url: '/fr/docs/reference/future/get-completed-file-and-line.html', label: 'getCompletedFileAndLine()' },
          { url: '/fr/docs/reference/future/get-completed-location.html', label: 'getCompletedLocation()' },
        ],
      },
      {
        url: '/fr/docs/components/context.html',
        label: 'Context',
        icon: 'link',
        children: [
          { url: '/fr/docs/reference/context/find.html', label: 'find()' },
          { url: '/fr/docs/reference/context/get.html', label: 'get()' },
          { url: '/fr/docs/reference/context/has.html', label: 'has()' },
          { url: '/fr/docs/reference/context/find-local.html', label: 'findLocal()' },
          { url: '/fr/docs/reference/context/get-local.html', label: 'getLocal()' },
          { url: '/fr/docs/reference/context/has-local.html', label: 'hasLocal()' },
          { url: '/fr/docs/reference/context/set.html', label: 'set()' },
          { url: '/fr/docs/reference/context/unset.html', label: 'unset()' },
        ],
      },
      { url: '/fr/docs/components/cancellation.html', label: 'Cancellation', icon: 'ban' },
      { url: '/fr/docs/components/zombie-coroutines.html', label: 'Coroutines zombies', icon: 'ghost' },
      { url: '/fr/docs/components/exceptions.html', label: 'Exceptions', icon: 'alert-triangle' },
      { url: '/fr/docs/components/interfaces.html', label: 'Interfaces', icon: 'plug' },
      {
        url: '/fr/docs/components/pool.html',
        label: 'Async\\Pool',
        icon: 'layers',
        children: [
          { url: '/fr/docs/reference/pool/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/pool/acquire.html', label: 'acquire()' },
          { url: '/fr/docs/reference/pool/try-acquire.html', label: 'tryAcquire()' },
          { url: '/fr/docs/reference/pool/release.html', label: 'release()' },
          { url: '/fr/docs/reference/pool/close.html', label: 'close()' },
          { url: '/fr/docs/reference/pool/is-closed.html', label: 'isClosed()' },
          { url: '/fr/docs/reference/pool/count.html', label: 'count()' },
          { url: '/fr/docs/reference/pool/idle-count.html', label: 'idleCount()' },
          { url: '/fr/docs/reference/pool/active-count.html', label: 'activeCount()' },
          { url: '/fr/docs/reference/pool/set-circuit-breaker-strategy.html', label: 'setCircuitBreakerStrategy()' },
          { url: '/fr/docs/reference/pool/get-state.html', label: 'getState()' },
          { url: '/fr/docs/reference/pool/activate.html', label: 'activate()' },
          { url: '/fr/docs/reference/pool/deactivate.html', label: 'deactivate()' },
          { url: '/fr/docs/reference/pool/recover.html', label: 'recover()' },
        ],
      },
      { url: '/fr/docs/components/pdo-pool.html', label: 'PDO Pool', icon: 'database' },
      {
        url: '/fr/docs/components/task-group.html',
        label: 'TaskGroup',
        icon: 'users',
        children: [
          { url: '/fr/docs/reference/task-group/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/task-group/spawn.html', label: 'spawn()' },
          { url: '/fr/docs/reference/task-group/spawn-with-key.html', label: 'spawnWithKey()' },
          { url: '/fr/docs/reference/task-group/await-completion.html', label: 'awaitCompletion()' },
          { url: '/fr/docs/reference/task-group/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/task-group/dispose.html', label: 'dispose()' },
          { url: '/fr/docs/reference/task-group/finally.html', label: 'finally()' },
          { url: '/fr/docs/reference/task-group/seal.html', label: 'seal()' },
          { url: '/fr/docs/reference/task-group/is-finished.html', label: 'isFinished()' },
          { url: '/fr/docs/reference/task-group/is-sealed.html', label: 'isSealed()' },
          { url: '/fr/docs/reference/task-group/count.html', label: 'count()' },
          { url: '/fr/docs/reference/task-group/get-results.html', label: 'getResults()' },
          { url: '/fr/docs/reference/task-group/get-errors.html', label: 'getErrors()' },
          { url: '/fr/docs/reference/task-group/get-iterator.html', label: 'getIterator()' },
          { url: '/fr/docs/reference/task-group/suppress-errors.html', label: 'suppressErrors()' },
          { url: '/fr/docs/reference/task-group/all.html', label: 'all()' },
          { url: '/fr/docs/reference/task-group/any.html', label: 'any()' },
          { url: '/fr/docs/reference/task-group/race.html', label: 'race()' },
        ],
      },
      {
        url: '/fr/docs/components/task-set.html',
        label: 'TaskSet',
        icon: 'list-checks',
        children: [
          { url: '/fr/docs/reference/task-set/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/task-set/spawn.html', label: 'spawn()' },
          { url: '/fr/docs/reference/task-set/spawn-with-key.html', label: 'spawnWithKey()' },
          { url: '/fr/docs/reference/task-set/join-next.html', label: 'joinNext()' },
          { url: '/fr/docs/reference/task-set/join-any.html', label: 'joinAny()' },
          { url: '/fr/docs/reference/task-set/join-all.html', label: 'joinAll()' },
          { url: '/fr/docs/reference/task-set/await-completion.html', label: 'awaitCompletion()' },
          { url: '/fr/docs/reference/task-set/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/task-set/dispose.html', label: 'dispose()' },
          { url: '/fr/docs/reference/task-set/finally.html', label: 'finally()' },
          { url: '/fr/docs/reference/task-set/seal.html', label: 'seal()' },
          { url: '/fr/docs/reference/task-set/is-finished.html', label: 'isFinished()' },
          { url: '/fr/docs/reference/task-set/is-sealed.html', label: 'isSealed()' },
          { url: '/fr/docs/reference/task-set/count.html', label: 'count()' },
          { url: '/fr/docs/reference/task-set/get-iterator.html', label: 'getIterator()' },
        ],
      },
      {
        url: '/fr/docs/components/filesystem-watcher.html',
        label: 'FileSystemWatcher',
        icon: 'eye',
        children: [
          { url: '/fr/docs/reference/filesystem-watcher/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/filesystem-watcher/close.html', label: 'close()' },
          { url: '/fr/docs/reference/filesystem-watcher/is-closed.html', label: 'isClosed()' },
          { url: '/fr/docs/reference/filesystem-watcher/get-iterator.html', label: 'getIterator()' },
        ],
      },
      {
        url: '/fr/docs/components/threads.html',
        label: 'Thread',
        icon: 'cpu',
        children: [
          { url: '/fr/docs/reference/spawn-thread.html', label: 'spawn_thread()' },
          { url: '/fr/docs/reference/thread/is-running.html', label: 'isRunning()' },
          { url: '/fr/docs/reference/thread/is-completed.html', label: 'isCompleted()' },
          { url: '/fr/docs/reference/thread/is-cancelled.html', label: 'isCancelled()' },
          { url: '/fr/docs/reference/thread/get-result.html', label: 'getResult()' },
          { url: '/fr/docs/reference/thread/get-exception.html', label: 'getException()' },
          { url: '/fr/docs/reference/thread/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/thread/finally.html', label: 'finally()' },
        ],
      },
      {
        url: '/fr/docs/components/thread-channels.html',
        label: 'ThreadChannel',
        icon: 'shuffle',
        children: [
          { url: '/fr/docs/reference/thread-channel/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/thread-channel/send.html', label: 'send()' },
          { url: '/fr/docs/reference/thread-channel/recv.html', label: 'recv()' },
          { url: '/fr/docs/reference/thread-channel/close.html', label: 'close()' },
          { url: '/fr/docs/reference/thread-channel/is-closed.html', label: 'isClosed()' },
          { url: '/fr/docs/reference/thread-channel/capacity.html', label: 'capacity()' },
          { url: '/fr/docs/reference/thread-channel/count.html', label: 'count()' },
          { url: '/fr/docs/reference/thread-channel/is-empty.html', label: 'isEmpty()' },
          { url: '/fr/docs/reference/thread-channel/is-full.html', label: 'isFull()' },
        ],
      },
      {
        url: '/fr/docs/components/thread-pool.html',
        label: 'ThreadPool',
        icon: 'workflow',
        children: [
          { url: '/fr/docs/reference/thread-pool/construct.html', label: '__construct()' },
          { url: '/fr/docs/reference/thread-pool/submit.html', label: 'submit()' },
          { url: '/fr/docs/reference/thread-pool/map.html', label: 'map()' },
          { url: '/fr/docs/reference/thread-pool/close.html', label: 'close()' },
          { url: '/fr/docs/reference/thread-pool/cancel.html', label: 'cancel()' },
          { url: '/fr/docs/reference/thread-pool/is-closed.html', label: 'isClosed()' },
          { url: '/fr/docs/reference/thread-pool/get-pending-count.html', label: 'getPendingCount()' },
          { url: '/fr/docs/reference/thread-pool/get-running-count.html', label: 'getRunningCount()' },
          { url: '/fr/docs/reference/thread-pool/get-completed-count.html', label: 'getCompletedCount()' },
          { url: '/fr/docs/reference/thread-pool/get-worker-count.html', label: 'getWorkerCount()' },
        ],
      },
    ],
  },
  {
    title: 'Reference des fonctions',
    icon: 'section-code',
    items: [
      { url: '/fr/docs/reference/supported-functions.html', label: 'Fonctions supportees' },
      { url: '/fr/docs/reference/spawn.html', label: 'spawn()' },
      { url: '/fr/docs/reference/spawn-with.html', label: 'spawn_with()' },
      { url: '/fr/docs/reference/await.html', label: 'await()' },
      { url: '/fr/docs/reference/await-all-or-fail.html', label: 'await_all_or_fail()' },
      { url: '/fr/docs/reference/await-all.html', label: 'await_all()' },
      { url: '/fr/docs/reference/await-any-or-fail.html', label: 'await_any_or_fail()' },
      { url: '/fr/docs/reference/await-first-success.html', label: 'await_first_success()' },
      { url: '/fr/docs/reference/await-any-of-or-fail.html', label: 'await_any_of_or_fail()' },
      { url: '/fr/docs/reference/await-any-of.html', label: 'await_any_of()' },
      { url: '/fr/docs/reference/iterate.html', label: 'iterate()' },
      { url: '/fr/docs/reference/suspend.html', label: 'suspend()' },
      { url: '/fr/docs/reference/delay.html', label: 'delay()' },
      { url: '/fr/docs/reference/timeout.html', label: 'timeout()' },
      { url: '/fr/docs/reference/protect.html', label: 'protect()' },
      { url: '/fr/docs/reference/current-coroutine.html', label: 'current_coroutine()' },
      { url: '/fr/docs/reference/current-context.html', label: 'current_context()' },
      { url: '/fr/docs/reference/coroutine-context.html', label: 'coroutine_context()' },
      { url: '/fr/docs/reference/root-context.html', label: 'root_context()' },
      { url: '/fr/docs/reference/get-coroutines.html', label: 'get_coroutines()' },
      { url: '/fr/docs/reference/signal.html', label: 'signal()' },
      { url: '/fr/docs/reference/graceful-shutdown.html', label: 'graceful_shutdown()' },
    ],
  },
  {
    title: 'Intégrations',
    icon: 'section-puzzle',
    items: [
      {
        url: '/fr/docs/frankenphp.html',
        label: 'FrankenPHP',
        icon: 'server',
        children: [
          { url: '/fr/docs/reference/frankenphp/request.html', label: 'Request' },
          { url: '/fr/docs/reference/frankenphp/response.html', label: 'Response' },
          { url: '/fr/docs/reference/frankenphp/uploaded-file.html', label: 'UploadedFile' },
        ],
      },
    ],
  },
  {
    title: 'Recherche',
    icon: 'section-flask',
    items: [
      { url: '/fr/docs/evidence/concurrency-efficiency.html', label: 'IO-Bound vs CPU-bound' },
      { url: '/fr/docs/evidence/coroutines-evidence.html', label: 'Pourquoi les coroutines fonctionnent' },
      { url: '/fr/docs/evidence/real-world-statistics.html', label: 'Statistiques de concurrence' },
      { url: '/fr/docs/evidence/swoole-evidence.html', label: 'Swoole en pratique' },
      { url: '/fr/docs/evidence/python-evidence.html', label: 'Python asyncio' },
    ],
  },
]

export const architectureSidebarFr: NavGroup[] = [
  {
    title: 'Noyau',
    icon: 'zap',
    items: [
      { url: '/fr/architecture.html', label: "Vue d'ensemble" },
      { url: '/fr/architecture/zend-async-api.html', label: 'TrueAsync ABI' },
      { url: '/fr/architecture/scheduler-reactor.html', label: 'Scheduler & Reactor' },
      { url: '/fr/architecture/events.html', label: 'Evenements' },
      { url: '/fr/architecture/waker.html', label: 'Waker' },
      { url: '/fr/architecture/async-gc.html', label: 'Ramasse-miettes' },
      { url: '/fr/architecture/fibers.html', label: 'Fibers' },
    ],
  },
  {
    title: 'Composants',
    icon: 'section-blocks',
    items: [
      { url: '/fr/architecture/pool.html', label: 'Async\\Pool' },
      { url: '/fr/architecture/pdo-pool.html', label: 'PDO Pool' },
    ],
  },
  {
    title: 'Integrations',
    icon: 'section-puzzle',
    items: [
      { url: '/fr/architecture/frankenphp.html', label: 'FrankenPHP' },
    ],
  },
]
