import os

translations = {
    "Garbage Collection in a Separate Coroutine": "Recoleccion de basura en una corrutina separada",
    "Event &#8594; Callback &#8594; Coroutine": "Evento &#8594; Callback &#8594; Corrutina",
    "Event Lifecycle": "Ciclo de vida del evento",
    "Overview: FrankenPHP + TrueAsync": "Descripcion general: FrankenPHP + TrueAsync",
    "Dual Notification System": "Sistema de notificacion dual",
    "Request Lifecycle": "Ciclo de vida de la solicitud",
    "PDO Pool &#8212; Components": "Pool PDO &#8212; Componentes",
    "Creating a Connection from the Pool": "Creacion de una conexion desde el pool",
    "Connection Lifecycle in the Pool": "Ciclo de vida de la conexion en el pool",
    "acquire() &#8212; Internal Algorithm": "acquire() &#8212; Algoritmo interno",
    "Circuit Breaker States": "Estados del Circuit Breaker",
    "Pool Data Structures": "Estructuras de datos del pool",
    "Full Cycle: acquire &#8594; use &#8594; release": "Ciclo completo: acquire &#8594; use &#8594; release",
    "Healthcheck &#8212; Periodic Verification": "Healthcheck &#8212; Verificacion periodica",
    "release() &#8212; Internal Algorithm": "release() &#8212; Algoritmo interno",
    "Scheduler and Reactor Interaction": "Interaccion entre Scheduler y Reactor",
    "Scheduler Main Loop": "Bucle principal del Scheduler",
    "Coroutine Suspend and Resume": "Suspension y reanudacion de corrutinas",
    "Waker States": "Estados del Waker",
    "Connection Lifecycle in Pool": "Ciclo de vida de la conexion en el pool",
    "Resource Lifecycle": "Ciclo de vida del recurso",
    "Coroutine A": "Corrutina A",
    "Coroutine B": "Corrutina B",
    "Coroutine": "Corrutina",
    "Scheduler": "Planificador",
    "GC Coroutine": "Corrutina GC",
    "Dtor Coroutine": "Corrutina Dtor",
    "GC Threshold Reached": "Umbral de GC alcanzado",
    "Calling Destructors": "Llamando destructores",
    "buffer full": "bufer lleno",
    "continues execution": "continua la ejecucion",
    "is not blocked,": "no esta bloqueada,",
    "marking, collection": "marcado, recoleccion",
    "awaits dtor_scope": "espera dtor_scope",
    "call destructor": "llamar destructor",
    "Destructor called await": "El destructor llamo a await",
    "Destructor awaits I/O": "El destructor espera E/S",
    "switch to another coroutine": "cambiar a otra corrutina",
    "dtor_scope completed": "dtor_scope completado",
    "freeing memory": "liberando memoria",
    "working...": "trabajando...",
    "new dtor coroutine": "nueva corrutina dtor",
    "continue": "continuar",
    "from dtor_idx": "desde dtor_idx",
    "Subscription": "Suscripcion",
    "Wakeup": "Despertar",
    "Resumption": "Reanudacion",
    "Coroutine sleeps": "La corrutina duerme",
    "Coroutine continues": "La corrutina continua",
    "with waker->result": "con waker->result",
    "enqueue in Scheduler": "encolar en el Planificador",
    "libuv callback": "callback de libuv",
    "Cleanup subscription": "Limpiar suscripcion",
    "Created": "Creado",
    "Active": "Activo",
    "Triggered": "Activado",
    "Closed": "Cerrado",
    "Stopped": "Detenido",
    "new event": "nuevo evento",
    "subscription not possible": "suscripcion no posible",
    "triggered_events updated": "triggered_events actualizado",
    "All requests pass through": "Todas las solicitudes pasan",
    "Go Runtime": "Tiempo de ejecucion Go",
    "Inter-Process Communication": "Comunicacion entre procesos",
    "PHP Runtime (TrueAsync)": "Tiempo de ejecucion PHP (TrueAsync)",
    "Caddy HTTP Server": "Servidor HTTP Caddy",
    "Dispatcher": "Despachador",
    "HTTP request": "Solicitud HTTP",
    "HTTP response": "Respuesta HTTP",
    "fd ready": "fd listo",
    "spawn": "generar",
    "Fast Path: Scheduler is Active": "Ruta rapida: el Planificador esta activo",
    "Slow Path: All Coroutines are Sleeping": "Ruta lenta: todas las corrutinas duermen",
    "send request": "enviar solicitud",
    "Called on": "Llamado en",
    "each Scheduler": "cada ciclo del",
    "tick": "Planificador",
    "No system": "Sin llamadas",
    "calls,": "al sistema,",
    "minimal": "latencia",
    "latency": "minima",
    "wakes up": "se despierta",
    "only on": "solo por",
    "notification": "notificacion",
    "spawn coroutine": "generar corrutina",
    "epoll/kqueue wakeup": "despertar epoll/kqueue",
    "HTTP request from client": "Solicitud HTTP del cliente",
    "Round-Robin: select PHP thread": "Round-Robin: seleccionar hilo PHP",
    "Thread buffer full?": "Bufer del hilo lleno?",
    "All buffers full?": "Todos los buferes llenos?",
    "HTTP 503 Service Unavailable": "HTTP 503 Servicio no disponible",
    "Try next thread": "Intentar siguiente hilo",
    "Send to requestChan": "Enviar a requestChan",
    "Channel was empty?": "El canal estaba vacio?",
    "PHP thread": "Hilo PHP",
    "already active": "ya activo",
    "Wake up": "Despertar",
    "event loop": "bucle de eventos",
    "Scheduler detected request": "Planificador detecto solicitud",
    "Create Scope for request": "Crear Scope para la solicitud",
    "Create coroutine": "Crear corrutina",
    "Call onRequest callback": "Llamar callback onRequest",
    "read request": "leer datos de",
    "data": "la solicitud",
    "async/await,": "async/await,",
    "parallel I/O": "E/S paralela",
    "Process business logic": "Procesar logica de negocio",
    "HTTP response to client": "Respuesta HTTP al cliente",
    "Release Scope and resources": "Liberar Scope y recursos",
    "User Code": "Codigo de usuario",
    "PDO Core (php-src)": "Nucleo PDO (php-src)",
    "Async Extension": "Extension Async",
    "Connection Pool": "Pool de conexiones",
    "Coroutines": "Corrutinas",
    "PDO Object": "Objeto PDO",
    "(template)": "(plantilla)",
    "inner": "interno",
    "manages": "gestiona",
    "stores": "almacena",
    "acquire / release": "adquirir / liberar",
    "bound": "vinculado",
    "Template does NOT connect to the DB.": "La plantilla NO se conecta a la BD.",
    "It stores credentials and settings": "Almacena credenciales y configuraciones",
    "for creating real connections.": "para crear conexiones reales.",
    "Coroutine calls": "La corrutina llama",
    "Connection exists for this coroutine?": "Existe conexion para esta corrutina?",
    "Return existing": "Devolver existente",
    "Pool has idle connections?": "El pool tiene conexiones inactivas?",
    "Take from pool": "Tomar del pool",
    "Pool at max size?": "Pool al tamano maximo?",
    "Wait for release": "Esperar liberacion",
    "Create new connection": "Crear nueva conexion",
    "Bind to coroutine": "Vincular a corrutina",
    "Execute SQL query": "Ejecutar consulta SQL",
    "Return result": "Devolver resultado",
    "Coroutine completed": "Corrutina completada",
    "Release connection": "Liberar conexion",
    "Healthcheck passed?": "Healthcheck superado?",
    "Return to idle list": "Devolver a lista inactiva",
    "Destroy connection": "Destruir conexion",
    "Pool closed?": "Pool cerrado?",
    "throw PoolException": "lanzar PoolException",
    "Has idle resource?": "Hay recurso inactivo?",
    "Can create new?": "Se puede crear uno nuevo?",
    "Extract from idle list": "Extraer de lista inactiva",
    "Call factory()": "Llamar factory()",
    "Return resource": "Devolver recurso",
    "Timeout exceeded": "Tiempo excedido",
    "throw TimeoutException": "lanzar TimeoutException",
    "ACTIVE": "ACTIVO",
    "INACTIVE": "INACTIVO",
    "HALF_OPEN": "SEMI_ABIERTO",
    "acquire() &#8212; allowed": "acquire() &#8212; permitido",
    "acquire() &#8212; blocked": "acquire() &#8212; bloqueado",
    "acquire() &#8212; trial": "acquire() &#8212; prueba",
    "Failures exceed threshold": "Fallos exceden umbral",
    "Cooldown timer expired": "Temporizador de enfriamiento expirado",
    "Trial request succeeds": "Solicitud de prueba exitosa",
    "Trial request fails": "Solicitud de prueba fallida",
    "One trial request allowed": "Una solicitud de prueba permitida",
    "User code": "Codigo de usuario",
    "Resource": "Recurso",
    "In use": "En uso",
    "Release": "Liberar",
    "Idle": "Inactivo",
    "Destroy": "Destruir",
    "Timer fired": "Temporizador disparado",
    "Extract resource": "Extraer recurso",
    "returned true?": "devolvio true?",
    "Return to pool": "Devolver al pool",
    "Destroy resource": "Destruir recurso",
    "More resources?": "Mas recursos?",
    "Done": "Hecho",
    "passed": "superado",
    "failed": "fallido",
    "(idle)": "(inactivo)",
    "Before release callback": "Callback antes de liberar",
    "to CircuitBreaker": "al CircuitBreaker",
    "Resource valid?": "Recurso valido?",
    "Waiters in queue?": "Hay esperas en la cola?",
    "Give to waiter": "Dar al que espera",
    "Add to idle list": "Agregar a lista inactiva",
    "Scheduler started": "Planificador iniciado",
    "FIFO order.": "Orden FIFO.",
    "Exception interrupts processing.": "La excepcion interrumpe el procesamiento.",
    "Process": "Procesar",
    "HI_PRIORITY coroutines": "corrutinas HI_PRIORITY",
    "Process FIFO queue": "Procesar cola FIFO",
    "Process microtasks": "Procesar microtareas",
    "Process timers": "Procesar temporizadores",
    "Tick reactor": "Tick del reactor",
    "Poll I/O events": "Consultar eventos de E/S",
    "All coroutines finished?": "Todas las corrutinas terminaron?",
    "Exit": "Salir",
    "More coroutines?": "Mas corrutinas?",
    "(executing)": "(ejecutando)",
    "(suspended)": "(suspendido)",
    "awaits I/O": "espera E/S",
    "I/O completed": "E/S completada",
    "Coroutine A suspends": "La corrutina A se suspende",
    "Coroutine B executes": "La corrutina B se ejecuta",
    "Coroutine A resumes": "La corrutina A se reanuda",
    "save state": "guardar estado",
    "restore state": "restaurar estado",
    "Yield to Scheduler": "Ceder al Planificador",
    "Waker is not active": "El Waker no esta activo",
    "Coroutine is executing": "La corrutina se esta ejecutando",
    "Waker is waiting": "El Waker esta esperando",
    "Coroutine is suspended": "La corrutina esta suspendida",
    "Operation completed": "Operacion completada",
    "Result is available": "El resultado esta disponible",
    "Operation was cancelled": "La operacion fue cancelada",
    "Exception is stored": "La excepcion esta almacenada",
    "Waker created": "Waker creado",
    "Initial state": "Estado inicial",
    "Final state": "Estado final",
    "Is there a connection": "Hay una conexion",
    "for this coroutine?": "para esta corrutina?",
    "Use existing": "Usar existente",
    "connection": "conexion",
    "Acquire from pool": "Adquirir del pool",
    "Coroutine ends": "La corrutina termina",
    "Auto-release": "Liberacion automatica",
    "Is there a free resource?": "Hay un recurso libre?",
    "Use resource": "Usar recurso",
    "Create new": "Crear nuevo",
    "Max pool size?": "Tamano maximo del pool?",
    "Wait": "Esperar",
    "with timeout": "con timeout",
    "Active use": "Uso activo",
    "Resource healthy?": "Recurso saludable?",
    "Return to idle": "Devolver a inactivo",
    "yes": "si",
    "no": "no",
    "microtask &#8594; spawn": "microtarea &#8594; generar",
    "periodic timer, poll": "temporizador periodico, poll",
    "NOTIFY_AND_CLOSE": "NOTIFY_AND_CLOSE",
    "(DNS, exec, Future)": "(DNS, exec, Future)",
}

src_base = "E:/php/true-async.github.io/diagrams/en"
dst_base = "E:/php/true-async.github.io/diagrams/es"

count = 0
for root, dirs, files in os.walk(src_base):
    for fname in sorted(files):
        if not fname.endswith(".svg"):
            continue
        src_path = os.path.join(root, fname)
        rel_path = os.path.relpath(src_path, src_base)
        dst_path = os.path.join(dst_base, rel_path)

        os.makedirs(os.path.dirname(dst_path), exist_ok=True)

        with open(src_path, "r", encoding="utf-8") as f:
            content = f.read()

        sorted_trans = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)

        for eng, esp in sorted_trans:
            content = content.replace(">" + eng + "<", ">" + esp + "<")
            content = content.replace("<title>" + eng + "</title>", "<title>" + esp + "</title>")

        with open(dst_path, "w", encoding="utf-8") as f:
            f.write(content)

        count += 1
        print(f"Translated: {rel_path}")

print(f"\nTotal: {count} SVGs translated")
